version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    environment:
      RACK_ENV: production
      RAILS_SERVE_STATIC_FILES: "false"
      SECRET_KEY_BASE: bundle exec rake secret
    ports:
      - "80:3000"
