livereload:
  image: devcrea/livereload
  ports:
    - "35729:35729"
  volumes:
    - ./app:/usr/src/livereload-watch

web:
  build: .
  dockerfile: Dockerfile.development
  ports:
    - "80:3000"
  links:
    - livereload
